#!/usr/bin/env node
require( '../../env.js' )();
var debug = require( 'debug' )( 'elastic-api' );

var ElasticSearch = require( '../src/elastic-search-api.js' );

var elasticInterface = ElasticSearch();

debug( 'elastic interface' )
debug( elasticInterface.elastic.get )

// elasticInterface.elastic
//   .getMapping(
//     'edu.risd.systems',
//     'events',
//     function response (error, results) {
//       debug('response')
//       debug(error)
//       debug(results)
//     } )

elasticInterface.elastic
  .get(
    'edu.risd.systems',
    'events',
    '-KWhqiEeoPc8xeDAHJ1t',
    function response ( error, results ) {
      debug( 'response' )
      debug( error )
      debug( results )
    } )
