#!/usr/bin/env node
require( '../../env.js' )();
var debug = require( 'debug' )( 'spawn-tasks-firebase' );

var firebase = require( 'firebase' );

var CreateTasks = require( '../src/firebase-tasks.js' );

var firebaseProject = process.env.FIREBASE_PROJECT;
var firebaseServiceAccount = JSON.parse(process.env.FIREBASE_SERVICE_ACCOUNT);

var app = firebase.initializeApp({
  serviceAccount: firebaseServiceAccount,
  databaseURL: "https://" + firebaseProject + ".firebaseio.com",
});

var create = CreateTasks( app );

create.addIndex(
  'test.risd.systems',
  'employees',
  JSON.stringify(
    { name: "Scrotie", colleague_status: "active" }),
  '-randon-sequence-1',
  false )

create.addIndex(
  'test.risd.systems',
  'employees',
  JSON.stringify(
    { name: "Nads", colleague_status: "active" }),
  '-randon-sequence-2',
  false )

create.deleteIndex(
  'test.risd.systems',
  'employees',
  '-randon-sequence-1' )

create.deleteIndex(
  'test.risd.systems',
  'employees',
  '-randon-sequence-2' )
