#!/usr/bin/env node
require( '../../env.js' )();
var debug = require( 'debug' )( 'spawn-tasks-stream' );

var ElasticSearchSync = require( '../stream-interface.js' );

var search = ElasticSearchSync();

search.addIndex(
  'employees',
  JSON.stringify(
    { name: "Scrotie", colleague_status: "active" }),
  '-randon-sequence-1',
  false )

search.addIndex(
  'employees',
  JSON.stringify(
    { name: "Nads", colleague_status: "active" }),
  '-randon-sequence-2',
  false )

search.deleteIndex(
  'employees',
  '-randon-sequence-1' )

search.deleteIndex(
  'employees',
  '-randon-sequence-2' )
